export const items = [
  {
    name: "Nizam Ki Jail Mein",
    hindiName: "निज़ाम की जेल में",
    englishName: "In the Prison of Nizam",
    imagePath: "book-covers/Nizam-Ki-Jail-Me.jpg",
    categoryID: "1",
    ctaLink: "/books/nizam-ki-jail-me",
  },
  // {
  //   name: "Bangladesh - Swatantrata Ke Baad",
  //   hindiName: "बांग्लादेश - स्वतंत्रता के बाद",
  //   englishName: "Bangladesh - After Independence",
  //   imagePath: "book-covers/Bangladesh---Swatantrata-Ke-Baad.jpg",
  //   categoryID: "4",
  //   ctaLink: "/books/bangladesh-swatantrata-ke-baad",
  // },
  {
    name: "Bangladesh - Swatantrata Ke Baad",
    hindiName: "बांग्लादेश - स्वतंत्रता के बाद",
    englishName: "Bangladesh - After Independence",
    imagePath: "book-covers/Bangladesh---Swatantrata-Ke-Baad.jpg",
    categoryID: "4",
    ctaLink: "/books/Bangladesh-Swatantrata-Ke",
  },
  {
    name: "Bharat Ko Hindu Rajya Ghoshit Karo",
    hindiName: "भारत को हिन्दू राज्य घोषित करो",
    englishName: "Declare India a Hindu Nation",
    imagePath: "book-covers/Bharat-Ko-Hindu-Rajya-Ghoshit-Karo.jpg",
    categoryID: "2",
    ctaLink: "/books/bharat-ko-hindu-rajya-ghoshit-karo",
  },
  {
    name: "Chayanika",
    hindiName: "चयनिका",
    englishName: "Selected Articles",
    imagePath: "book-covers/Chayanika.jpg",
    categoryID: "3",
    ctaLink: "/books/chayanika",
  },
  {
    name: "Devtaa Kursi Ke",
    hindiName: "देवता कुर्सी के",
    englishName: "Gods of Chair",
    imagePath: "book-covers/Devta-Kursi-Ke.jpg",
    categoryID: "5",
    ctaLink: "/books/devta-kursi-ke",
  },
  {
    name: "Arya-Satyagrah Mein Gurukul Ki Aahuti",
    hindiName: "आर्य-सत्याग्रह में गुरुकुल की आहुति",
    englishName: "Gurukul’s Offering in Arya Satyagrah",
    imagePath: "book-covers/Gurukul-Ki-Ahuuti.jpg",
    categoryID: "1",
    ctaLink: "/books/gurukul-ki-aahuti",
  },
  {
    name: "Hindi Hi Kyon ?",
    hindiName: "हिंदी ही क्यों ?",
    englishName: "Why Hindi ?",
    imagePath: "book-covers/HindiHeeKyon.jpg",
    categoryID: "2",
    ctaLink: "/books/hindi-hee-kyon/",
  },
  // {
  //   name: "Kashmir - Jhulasta Swarg",
  //   hindiName: "कश्मीर - झुलसता स्वर्ग",
  //   englishName: "Kashmir - Scorching Paradise",
  //   imagePath: "book-covers/Kashmir.jpg",
  //   categoryID: "2",
  //   ctaLink: "/books/kashmir",
  // },
  {
    name: "Kashmir - Jhulasta Swarg",
    hindiName: "कश्मीर - झुलसता स्वर्ग",
    englishName: "Kashmir - Scorching Paradise",
    imagePath: "book-covers/Kashmir.jpg",
    categoryID: "2",
    ctaLink: "/books/Kashmir-Jhulasta-Swarg",
  },
  {
    name: "Pandim Ke Durgam Path Par",
    hindiName: "पण्डिम के दुर्गम पथ पर",
    englishName: "Expedition to Inaccessible Pandim",
    imagePath: "book-covers/Pandim-ke-Durgam-Path-Par.jpg",
    categoryID: "4",
    ctaLink: "/books/pandim-ke-durgam-path-par",
  },
  {
    name: "Rashtriya Ekta Ki Buniyaden",
    hindiName: "राष्ट्रीय एकता की बुनियादें",
    englishName: "Foundations of National Integration",
    imagePath: "book-covers/Rashtriya-Ekta-ki-Buniyaden.jpg",
    categoryID: "2",
    ctaLink: "/books/rashtriya-ekta-ki-buniyaden",
  },
  {
    name: "Rashtriya Patrakarita Ke Purodha",
    hindiName: "राष्ट्रीय पत्रकारिता के पुरोधा",
    englishName: "Master of Patriotic Journalism",
    imagePath: "book-covers/Rashtriya-Patrakarita-Ke-Purodha.jpg",
    categoryID: "3",
    ctaLink: "/books/rashtriya-patrakarita-ke-purodha",
  },
  {
    name: "Storm in Punjab",
    hindiName: "स्टॉर्म इन पंजाब",
    englishName: "Storm in Punjab",
    imagePath: "book-covers/Storm-in-Punjab.jpg",
    categoryID: "2",
    ctaLink: "/books/storm-in-punjab",
  },
  // {
  //   name: "Toofan Ke Daur Se - Punjab",
  //   hindiName: "तूफ़ान के दौर से - पंजाब",
  //   englishName: "During the storm - Punjab",
  //   imagePath: "book-covers/Toofan-Ke-Daur-Se.jpg",
  //   categoryID: "2",
  //   ctaLink: "/books/toofan-ke-daur-se-punjab",
  // },
  {
    name: "Toofan Ke Daur Se Punjab",
    hindiName: "तूफ़ान के दौर से - पंजाब",
    englishName: "During the storm - Punjab",
    imagePath: "book-covers/Toofan-Ke-Daur-Se.jpg",
    categoryID: "2",
    ctaLink: "/books/Toofan-Ke-Daur-Se",
  },
  {
    name: "Uttarakhand Ke Path Par",
    hindiName: "उत्तराखंड के पथ पर",
    englishName: "On the Way to Uttarakhand",
    imagePath: "book-covers/UttrakhandKePathPar.jpg",
    categoryID: "4",
    ctaLink: "/books/uttarakhand-ke-path-par",
  },
  {
    name: "Rajneeti Nahi, Rashtraneeti",
    hindiName: "राजनीति नहीं, राष्ट्रनीति",
    englishName: "National Interest, Not Politics",
    imagePath: "book-covers/Raaajneeti-nahi-rashraneeti.jpg",
    categoryID: "2",
    ctaLink: "/books/rajneeti-nahi-rashtraneeti",
  },
  
  {
    name: "Gandhi ka Hasya-Vinod",
    hindiName: "गाँधी का हास्य विनोद",
    englishName: "The Humour of Gandhi Ji",
    imagePath: "book-covers/Gandhi-ka-Hasya-Vinod.jpg",
    categoryID: "5",
    ctaLink: "/books/gandhi-ji-ka-hasya-vinod",
  },
  {
    name: "Svetlana",
    hindiName: "स्वेतलाना",
    englishName: "Svetlana",
    imagePath: "book-covers/Swetlana.jpg",
    categoryID: "5",
    ctaLink: "/books/svetlana",
  },
  {
    name: "Arya-Samaj Ki Vichaar-Dhaaraa",
    hindiName: "आर्य समाज की विचारधारा",
    englishName: "The Ideology of Arya Samaj",
    imagePath: "book-covers/Arya-Samaj.jpg",
    categoryID: "1",
    ctaLink: "/books/aryasamaj-ki-vichardhara",
  },
  {
    name: "Jati Bhed ka Abhishaap",
    hindiName: "जातिभेद का अभिशाप",
    englishName: "The Curse of Caste System",
    imagePath: "book-covers/JaatiBhedAbhishaap.jpg",
    categoryID: "2",
    ctaLink: "/books/jati-bhed-ka-abhishaap",
  },
  {
    name: "Aapt Rastra Purush",
    hindiName: "आप्त राष्ट्र पुरुष",
    englishName: "True National Figure",
    imagePath: "book-covers/aapt-rastra-purush.jpg",
    categoryID: "1",
    ctaLink: "/books/aapt-rastra-purush",
  },
  {
    name: "Asliyat Kya Hai",
    hindiName: "असलियत क्या है",
    englishName: "The Reality",
    imagePath: "book-covers/asliyat.jpg",
    categoryID: "2",
    ctaLink: "/books/asliyat-kya-hai",
  },
  {
    name: "Hind Kee Chaadar Mein Daag",
    hindiName: "हिन्द की चादर में दाग",
    englishName: "Stain on India",
    imagePath: "book-covers/Hind-kee-chaadar-mein-daag.jpg",
    categoryID: "2",
    ctaLink: "/books/Hind-Kee-Chaadar-Mein-Daag",
  },
  {
    name: "O Mere Rajhans!",
    hindiName: "ओ मेरे राजहंस",
    englishName: "O My Swan!",
    imagePath: "book-covers/O-mere-rajhans.jpg",
    categoryID: "5",
    ctaLink: "/books/o-mere-rajhans",
  },
  {
    name: "Phir Is Andaaz, Se Bahaar Aayi",
    hindiName: "फिर इस अंदाज़ से बहार आयी",
    englishName: "Spring Again, in Style!",
    imagePath: "book-covers/Phir-iss-andaz-se-bahar-aayi.jpg",
    categoryID: "5",
    ctaLink: "/books/phir-is-andaaz-se-bahar-aayi",
  },
  {
    name: "Divya Dayanand",
    hindiName: "दिव्य दयानन्द",
    englishName: "Divine Dayanand",
    imagePath: "book-covers/Divya-Dayanand.jpg",
    categoryID: "1",
    ctaLink: "/books/divya-dayanand",
  },
  {
    name: "Ishwar - Vaigyaanikon Ki Drishti Mein",
    hindiName: "ईश्वर - वैज्ञानिकों की दृष्टि में",
    englishName: "God - In the Eyes of Scientists",
    imagePath: "book-covers/Ishwar.jpg",
    categoryID: "1",
    ctaLink: "/books/ishwar-vaijyanikon-ki-drishti-mein",
  },
  {
    name: "Satvalekar Felicitation Digest",
    hindiName: "सातवलेकर अभिनन्दन ग्रन्थ",
    englishName: "Satvalekar Felicitation Digest",
    imagePath: "book-covers/Satavlekar-Abhinandan-Granth.jpg",
    categoryID: "1",
    ctaLink: "/books/Satavlekar-Abhinandan-Granth",
  },
  {
    name: "Mauritius Memorial Digest",
    hindiName: "मॉरीशस स्मारक 1974",
    englishName: "Mauritius Memorial Digest",
    imagePath: "book-covers/Mauritius-Smarika-1974_compressed.jpg",
    categoryID: "1",
    ctaLink: "/books/Mauritius-Smarika-1974",
  },
  {
    name: "London Memorial Digest",
    hindiName: "लंदन स्मारिका",
    englishName: "London Memorial Digest",
    imagePath: "book-covers/London-Smarika_compressed.jpg",
    categoryID: "1",
    ctaLink: "/books/London-Smarika",
  },
]
export const items2 = [
  {
    name: "Introduction to Contents",
    hindiName: "",
    englishName: "",
    imagePath: "book.png",
    categoryID: "6",
    ctaLink: "/books/introduction-to-contents",
  },
  {
    name: "Desh Drishti",
    hindiName: "01. देश दृष्टि",
    englishName: "National Issues",
    imagePath: "book-covers/Desh-Drishti.jpg",
    categoryID: "6",
    ctaLink: "/books/desh-drishti",
  },
  {
    name: "Jaati-Dharm-Bhasha ki Sampradayikta",
    hindiName: "02. जाति-धर्म-भाषा की सांप्रदायिकता",
    englishName: "Communalism of Caste-Religion-Language",
    imagePath: "book-covers/Jaati-Dharam_bhasha.jpg",
    categoryID: "6",
    ctaLink: "/books/jaati-dharm-bhasha",
  },
  {
    name: "Praantiyata Aur Aatankwad",
    hindiName: "03. प्रांतीयता और आतंकवाद",
    englishName: "Provincialism and Terrorism",
    imagePath: "book-covers/Aatankwad.jpg",
    categoryID: "6",
    ctaLink: "/books/praantiyata-aur-aatankwad",
  },
  {
    name: "Rajneetik Uthapatak",
    hindiName: "04. राजनीतिक उठापटक",
    englishName: "Political  Gymnastic",
    imagePath: "book-covers/Rajneetik-Uthapatak.jpg",
    categoryID: "6",
    ctaLink: "/books/rajneetik-uthapatak",
  },
  {
    name: "Padosi Desh",
    hindiName: "05. पड़ौसी देश",
    englishName: "Neighbouring Countries",
    imagePath: "book-covers/Padosi-Desh.jpg",
    categoryID: "6",
    ctaLink: "/books/padosi-desh",
  },
  {
    name: "Vitta Neeti",
    hindiName: "06. वित्त नीति",
    englishName: "Economic Policy",
    imagePath: "book-covers/Vittneeti.jpg",
    categoryID: "6",
    ctaLink: "/books/vitta-neeti",
  },
  {
    name: "Vishwa Paridrisya - Videsh Neeti",
    hindiName: "07. विश्व परिदृस्य - विदेश नीति",
    englishName: "International Landscape/Foreign Policy",
    imagePath: "book-covers/Vishwa-Paridrisya-Videsh-Neeti.jpg",
    categoryID: "6",
    ctaLink: "/books/vishwa-paridrisya-videsh-neeti",
  },
  {
    name: "Rashtriya Sarkar",
    hindiName: "08. राष्ट्रीय सरकार",
    englishName: "National Government",
    imagePath: "book-covers/National-Government.jpg",
    categoryID: "6",
    ctaLink: "/books/rashtriya-sarkar",
  },
  {
    name: "Aadarsh Upay Aur Sujhav",
    hindiName: "09. आदर्श उपाय और सुझाव",
    englishName: "Ideal Solutions/Suggestions",
    imagePath: "book-covers/Aadarsh-Upay-aur-Sujhav.jpg",
    categoryID: "6",
    ctaLink: "/books/aadarsh-upay-aur-sujhav",
  },
  {
    name: "Rashtra-Prahari Arya Samaj",
    hindiName: "10. राष्ट्र-प्रहरी आर्य समाज",
    englishName: "National-Sentinel Arya Samaj",
    imagePath: "book-covers/Rashtaprahari.jpg",
    categoryID: "6",
    ctaLink: "/books/rashtra-prahari-arya-samaj",
  },
  {
    name: "Pt. Kshitish Vedalankar ki Kritiyan",
    hindiName: "11. पंडित क्षितीश वेदालंकार की कृतियां",
    englishName: "Books and Compilations of Pt. Kshitish Vedalankar",
    imagePath: "book-covers/pt-kshitiz-vedalankar-ki-kritya.jpg",
    categoryID: "6",
    ctaLink: "/books/pt-kshitish-vedalankar-ki-kritiyan",
  },
]

export const items3 = [
  {
    name: "Bujhati Raakh Mein Chamakti Chingariyan",
    hindiName: "बुझती राख में चमकती चिंगारियां",
    englishName: "Glowing Sparks in Smouldering Ashes",
    imagePath: "book-covers/Bujhati-Rakh-me-Chamaktee-Chingariyan.jpg",
    categoryID: "7",
    ctaLink: "/books/Bujhati-Rakh-me-Chamaktee-Chingariyan",
  },
  {
    name: "Toofan Ke Daur Se - Punjab",
    hindiName: "तूफ़ान के दौर से - पंजाब",
    englishName: "During the storm - Punjab",
    imagePath: "book-covers/Toofan-Ke-Daur-Se.jpg",
    categoryID: "7",
    ctaLink: "/books/toofan-ke-daur-se-punjab",
  },
]
export const items4 = [
  {
    name: "'Kashmir - Jhulasta Swarg' ke liye Anubhoomika",
    hindiName: "'कश्मीर - झुलसता स्वर्ग' के लिए अनुभूमिका",
    englishName: "Prologue for 'Kashmir - Scorching Paradise'",
    imagePath: "book-covers/Anubhumika-for-Kashmir-Khulasta-Swarg.jpg",
    categoryID: "8",
    ctaLink: "/books/Anubhumika-for-Kashmir-Khulasta-Swarg",
  },
  {
    name: "Kashmir - Jhulasta Swarg",
    hindiName: "कश्मीर - झुलसता स्वर्ग",
    englishName: "Kashmir - Scorching Paradise",
    imagePath: "book-covers/Kashmir.jpg",
    categoryID: "8",
    ctaLink: "/books/kashmir",
  },
]
export const items5 = [
  {
    name: "Swatantrata Ke Baad ke liye Anubhoomika",
    hindiName: "बँगला देश: स्वतंत्रता के बाद के लिए अनुभूमिका",
    englishName: "Prologue for 'Bangla Desh: After Independence'",
    imagePath: "book-covers/Bangladesh.jpg",
    categoryID: "9",
    ctaLink: "/books/Bangladesh-Anubhoomika",
  },
 {
    name: "Bangladesh - Swatantrata Ke Baad",
    hindiName: "बांग्लादेश - स्वतंत्रता के बाद",
    englishName: "Bangladesh - After Independence",
    imagePath: "book-covers/Bangladesh---Swatantrata-Ke-Baad.jpg",
    categoryID: "9",
    ctaLink: "/books/bangladesh-swatantrata-ke-baad",
  },
]

export const categories = [
  {
    id: "1",
    name: "Arya Samaj, Vedic Ideology, DAV movement",
    hindiName: "",
    englishName: "",
  },
  {
    id: "2",
    name: "National Issues, Hindi, Hindu, Hindustan",
    hindiName: "",
    englishName: "",
  },
  {
    id: "3",
    name: "Felicitations",
    hindiName: "",
    englishName: "",
  },
  {
    id: "4",
    name: "Travelogues",
    hindiName: "",
    englishName: "",
  },
  {
    id: "5",
    name: "In Lighter Vein, Satire",
    hindiName: "",
    englishName: "",
  },
  {
    id: "6",
    name: "Rajneeti Nahi RashtraNeeti",
    hindiName: "",
    englishName: "",
  },
  {
    id: "7",
    // name: "Toofan Ke Daur Se Punjab",
    hindiName: "",
    englishName: "",
  },
  {
    id: "8",
    // name: "Kashmir Jhulasta Swarg",
    hindiName: "",
    englishName: "",
  },
  {
    id: "9",
    // name: "Bangladesh Sawtantrata Ke Baad",
    hindiName: "",
    englishName: "",
  },
]
